steps:
  - label: ":hammer: Build"
    command: "make build_count_bits"
    key: build

  - label: ":test_tube: Test"
    command: "make count_bits"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: "echo deploying"
    key: deploy
    depends_on: test
